# Copyright (C) 2026 ETH Zurich and University of Bologna
# SPDX-License-Identifier: Apache-2.0
CASE ?= decode_b1_kv1024
CASES = $(DECODE_CASES)
include $(dir $(lastword $(MAKEFILE_LIST)))../Makefile
