#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Generate the original gather workload using the SDK preload-ELF convention."""
import argparse
import hashlib
import importlib.util
import json
import os
from pathlib import Path
import numpy as np
from elftools.elf.elffile import ELFFile
import preload


def load(path, cls):
    spec = importlib.util.spec_from_file_location(cls, path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return getattr(module, cls)()


def c_array(name, values, ctype):
    flat = values.reshape(-1)
    lines = [f'static const {ctype} {name}[{len(flat)}] = {{']
    for start in range(0, len(flat), 16):
        lines.append('    ' + ', '.join(str(int(x)) for x in flat[start:start+16]) + ',')
    return '\n'.join(lines + ['};', ''])


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('arch', type=Path)
    parser.add_argument('kernel', type=Path)
    parser.add_argument('app', type=Path)
    parser.add_argument('output', type=Path)
    args = parser.parse_args()
    arch, cfg = load(args.arch, 'FlexClusterArch'), load(args.kernel, 'SparseDma')
    if not (0 < cfg.selected <= cfg.rows <= 65536):
        raise ValueError('Require 0 < selected <= rows <= 65536 for packed 16-bit indices')
    row_bytes = cfg.dim * 2
    if row_bytes <= 0 or row_bytes & (row_bytes-1):
        raise ValueError('Gather row stride must be a power of two')
    if (arch.num_node_per_ctrl, arch.hbm_chan_placement, arch.hbm_node_aliase) != (1, [4,0,0,0], 1):
        raise ValueError('This sanity test requires one channel per west edge node, without aliases')
    if not arch.idma_gather_enable:
        raise ValueError('Enable the sparse index reader in the test architecture')
    # Same sequence as spatz-sparse-dma/sw/spatzBenchmarks/gather/script/gen_data.py.
    rng = np.random.default_rng(cfg.seed)
    matrix = rng.standard_normal((cfg.rows, cfg.dim)).astype('<f2').view('<u2')
    indices = np.sort(rng.choice(cfg.rows, size=cfg.selected, replace=False)).astype('<u4')
    golden = matrix[indices].copy()
    matrix_addr = arch.hbm_start_base + cfg.hbm_offset
    index_addr = (matrix_addr + matrix.nbytes + 63) & ~63
    if matrix_addr < arch.hbm_start_base or index_addr + indices.nbytes > min(1 << 32, arch.hbm_start_base + arch.hbm_node_addr_space):
        raise ValueError('Source and indices must fit the RV32-addressable west node 0 window')
    if golden.nbytes + indices.nbytes*2 + 512 > arch.cluster_tcdm_size:
        raise ValueError('The result and indices exceed the TCDM size')
    args.app.mkdir(parents=True, exist_ok=True)
    include = args.app / 'include'
    include.mkdir(exist_ok=True)
    args.output.mkdir(parents=True, exist_ok=True)
    checksum = 2166136261
    for value in golden.tobytes():
        checksum = ((checksum ^ value) * 16777619) & 0xffffffff
    (include / 'sparse_dma.h').write_text(
        '// Generated by sparse_dma_preload.py\n#pragma once\n#include <stdint.h>\n'
        f'#define SPARSE_ROWS {cfg.rows}U\n#define SPARSE_DIM {cfg.dim}U\n'
        f'#define SPARSE_SELECTED {cfg.selected}U\n'
        f'#define SPARSE_EXPECTED_CHECKSUM 0x{checksum:08x}U\n')
    (include / 'preload.h').write_text(
        '// Generated HBM addresses: west node 0\n#pragma once\n'
        f'#define SPARSE_MATRIX_ADDR ((uint64_t)0x{matrix_addr:x})\n'
        f'#define SPARSE_INDEX_ADDR ((uint64_t)0x{index_addr:x})\n')
    (include / 'golden.h').write_text('// Generated bit-exact FP16 reference\n#pragma once\n'
        + c_array('sparse_expected_indices', indices, 'uint32_t')
        + c_array('sparse_golden', golden, 'uint16_t'))
    # The SDK utility creates array.c/link.ld temporarily in its working directory.
    previous = Path.cwd()
    try:
        os.chdir(args.output)
        preload.make_preload_elf(str(args.app / 'preload.elf'),
                                [matrix, indices], [matrix_addr, index_addr])
    finally:
        os.chdir(previous)
    # Verify the utility produced real data, not an empty/stale preload artifact.
    with (args.app / 'preload.elf').open('rb') as stream:
        elf = ELFFile(stream)
        for address, data in ((matrix_addr, matrix.tobytes()), (index_addr, indices.tobytes())):
            segments = [s for s in elf.iter_segments() if s['p_type'] == 'PT_LOAD'
                        and s['p_vaddr'] <= address and address+len(data) <= s['p_vaddr']+s['p_filesz']]
            if len(segments) != 1:
                raise RuntimeError(f'Missing preload segment at {address:#x}')
            seg = segments[0]
            start = address - seg['p_vaddr']
            if seg.data()[start:start+len(data)] != data:
                raise RuntimeError('Preload ELF content differs from generated input')
    manifest = {'architecture': vars(arch), 'kernel': vars(cfg), 'matrix_addr': matrix_addr,
                'index_addr': index_addr, 'row_bytes': row_bytes, 'gather_bytes': golden.nbytes,
                'indices': indices.tolist(), 'expected_checksum': f'{checksum:08x}',
                'matrix_sha256': hashlib.sha256(matrix.tobytes()).hexdigest(),
                'indices_sha256': hashlib.sha256(indices.tobytes()).hexdigest(),
                'golden_sha256': hashlib.sha256(golden.tobytes()).hexdigest()}
    (args.output / 'workload.json').write_text(json.dumps(manifest, indent=2)+'\n')
    print(f'SPARSE_DMA_PRELOAD_PASS matrix=0x{matrix_addr:x} indices=0x{index_addr:x} bytes={golden.nbytes} checksum={checksum:08x}')


if __name__ == '__main__':
    main()
