#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Generate dense context addresses, local indices and a 64-bit preload ELF."""
import argparse
import hashlib
import importlib.util
import json
from pathlib import Path
import struct
import sys
import numpy as np
from elftools.elf.elffile import ELFFile

sys.path.insert(0, str(Path(__file__).resolve().parents[1]/'sparse_attn_access'))
from topology import hbm_layout

VARIANTS = ('core-loop', 'inlined-loop', 'hw-gather')
DATA_OFFSET = 0x100000  # Leave the SDK runtime's low HBM range available.
ROI_TYPE = 0x534141
ELF_SEGMENT_LIMIT = 60000


def load(path, name):
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return getattr(module, name)()


def fnv(data):
    value = 2166136261
    for byte in data:
        value = ((value ^ byte) * 16777619) & 0xffffffff
    return value


def token_data(cid, tokens, dim, element_bytes):
    values = (np.asarray(tokens, dtype=np.uint32)[:, None]
              ^ np.uint32((cid * 0x9e3779b9) & 0xffffffff)
              ^ (np.arange(dim, dtype=np.uint32)[None, :] * np.uint32(0x85ebca6b))
              ^ np.uint32(0xa5a55a5a))
    values ^= values >> 16
    values *= np.uint32(0x7feb352d)
    values ^= values >> 15
    if element_bytes == 2:
        return ((values & 0x3ff) | 0x3c00).astype('<u2')
    return ((values & 0x7fffff) | 0x3f800000).astype('<u4')


def prepare(arch_path, kernel_path, app, output):
    if any((output/variant/'run/exit-status.txt').exists() for variant in VARIANTS):
        raise ValueError('Saved runs exist; choose a fresh SPARSE_ATTN_OUTPUT before rebuilding')
    arch, cfg = load(arch_path, 'FlexClusterArch'), load(kernel_path, 'SparseAttnAccess')
    clusters = arch.num_cluster_x * arch.num_cluster_y
    layout = hbm_layout(vars(arch))
    nodes = len(layout)
    if cfg.token_dtype not in ('fp16', 'fp32'):
        raise ValueError('token_dtype must be fp16 or fp32')
    element_bytes = 2 if cfg.token_dtype == 'fp16' else 4
    token_bytes = cfg.token_dim * element_bytes
    if token_bytes <= 0 or token_bytes & (token_bytes-1):
        raise ValueError('The token size must be a power of two')
    if not 0 < cfg.selected_tokens <= cfg.context_tokens <= 0xffffffff:
        raise ValueError('Require 0 < N <= M <= 2^32-1')
    if not 0 <= cfg.selection_seed <= 0xffffffff or not arch.idma_gather_enable:
        raise ValueError('Require a 32-bit seed and enabled gather')
    pad_selected = (cfg.selected_tokens + 1) & ~1
    if cfg.selected_tokens * token_bytes + pad_selected * 8 + 4096 > arch.cluster_tcdm_size:
        raise ValueError('Selected output and local indices exceed cluster TCDM capacity')
    # Each aligned row occupies one private-backend AXI burst (4 KiB maximum).
    # Limit outstanding rows identically in all variants to avoid legacy queue exhaustion.
    if not 32 <= token_bytes <= 4096 or arch.idma_outstand_burst < 4:
        raise ValueError('Require 32..4096 bytes per token and at least four burst slots')
    batch = min(128, arch.idma_outstand_burst // 2)
    batch -= batch % 2
    if batch == 0:
        raise ValueError('Need at least four burst slots for aligned gather batches')
    per_node = [(cfg.context_tokens + nodes - 1 - node) // nodes for node in range(nodes)]
    if max(per_node) * clusters * token_bytes + DATA_OFFSET > arch.hbm_node_addr_space:
        raise ValueError('Dense contexts exceed an HBM node address window')
    output.mkdir(parents=True, exist_ok=True)
    include = app / 'include'
    include.mkdir(parents=True, exist_ok=True)
    constants = {
        'CLUSTERS': clusters, 'HBM_NODES': nodes, 'SELECTED': cfg.selected_tokens,
        'PAD_SELECTED': pad_selected, 'CONTEXT': cfg.context_tokens, 'TOKEN_DIM': cfg.token_dim,
        'ELEMENT_BYTES': element_bytes, 'TOKEN_BYTES': token_bytes, 'TOKEN_SHIFT': token_bytes.bit_length()-1,
        'SEED': cfg.selection_seed, 'SORTED': int(cfg.sorted_indices), 'BATCH': batch, 'ROI_TYPE': ROI_TYPE,
    }
    header = '// Generated by sparse_attn_access_preload.py\n#pragma once\n#include <stdint.h>\n'
    header += ''.join(f'#define SAA_{key} {value}U\n' for key, value in constants.items())
    header += f'#define SAA_STORAGE_TYPE uint{element_bytes*8}_t\n'
    for key, value in [('HBM_BASE', arch.hbm_start_base), ('HBM_WINDOW', arch.hbm_node_addr_space), ('HBM_OFFSET', DATA_OFFSET)]:
        header += f'#define SAA_{key} UINT64_C(0x{value:x})\n'
    (include / 'sparse_attn_access.h').write_text(header)
    selections, address_indices, users = [], [], []
    for cid in range(clusters):
        rng = np.random.default_rng(np.random.SeedSequence([cfg.selection_seed, cid]))
        tokens = rng.choice(cfg.context_tokens, cfg.selected_tokens, replace=False).astype('<u4')
        if cfg.sorted_indices:
            tokens.sort()
        addresses = np.array([layout[int(t) % nodes]['base'] + DATA_OFFSET
                              + (cid * per_node[int(t) % nodes] + int(t)//nodes) * token_bytes
                              for t in tokens], dtype=np.uint64)
        if int(addresses.max() // token_bytes) > 0xffffffff:
            raise ValueError('Physical row indices exceed the existing 32-bit gather format')
        mapped = (addresses // token_bytes).astype('<u4')
        data = token_data(cid, tokens, cfg.token_dim, element_bytes)
        selections.append(tokens)
        address_indices.append(mapped)
        users.append({'cluster': cid, 'indices': tokens.tolist(), 'address_indices': mapped.tolist(),
                      'checksum': f'{fnv(data.tobytes()):08x}',
                      'index_checksum': fnv(np.column_stack((tokens, mapped)).astype('<u4').tobytes()),
                      'payload_sha256': hashlib.sha256(data.tobytes()).hexdigest(),
                      'selected_per_node': np.bincount(tokens % nodes, minlength=nodes).tolist()})
    np.savez(output/'indices.npz', tokens=np.array(selections), address_indices=np.array(address_indices))
    manifest = {'architecture': vars(arch), 'kernel': vars(cfg), 'clusters': clusters, 'hbm_nodes': nodes,
                'hbm_node_layout': layout,
                'configuration_files': {'architecture': str(arch_path.resolve()), 'kernel': str(kernel_path.resolve())},
                'element_bytes': element_bytes, 'token_bytes': token_bytes, 'batch_tokens': batch,
                'roi_type': ROI_TYPE, 'hbm_data_offset': DATA_OFFSET, 'tokens_per_user_per_node': per_node,
                'context_bytes_per_user': cfg.context_tokens * token_bytes,
                'logical_context_bytes': clusters * cfg.context_tokens * token_bytes,
                'read_bytes': clusters * cfg.selected_tokens * token_bytes, 'users': users,
                'preload_policy': 'Initialize selected tokens and local index lists; unused context addresses are never accessed.'}
    (output/'workload.json').write_text(json.dumps(manifest, indent=2)+'\n')
    print(f'SAA_PREPARE_PASS clusters={clusters} HBM_nodes={nodes} N={cfg.selected_tokens} M={cfg.context_tokens} batch={batch}')


def write_elf(path, records):
    records.sort(key=lambda item: item[0])
    for a, b in zip(records, records[1:]):
        if a[0] + len(a[1]) > b[0]:
            raise ValueError('Preload address overlap')
    if len(records) >= 0xffff:
        raise ValueError('Too many ELF segments')
    ident = b'\x7fELF' + bytes([2, 1, 1]) + bytes(9)
    offset = (64 + 56*len(records) + 63) & ~63
    headers, payloads = [], []
    for address, data in records:
        headers.append(struct.pack('<IIQQQQQQ', 1, 6, offset, address, address, len(data), len(data), 8))
        payloads.append((offset, data))
        offset = (offset + len(data) + 7) & ~7
    with path.open('wb') as stream:
        stream.write(struct.pack('<16sHHIQQQIHHHHHH', ident, 2, 243, 1, 0, 64, 0, 0, 64, 56, len(records), 0, 0, 0))
        stream.write(b''.join(headers))
        for offset, data in payloads:
            stream.seek(offset)
            stream.write(data)
    with path.open('rb') as stream:
        elf = ELFFile(stream)
        for segment, (address, data) in zip(elf.iter_segments(), records):
            if segment['p_paddr'] != address or segment.data() != data:
                raise ValueError('Preload ELF verification failed')


def preload(output):
    manifest = json.loads((output/'workload.json').read_text())
    arch, cfg = manifest['architecture'], manifest['kernel']
    records = []
    for user in manifest['users']:
        data = token_data(user['cluster'], user['indices'], cfg['token_dim'], manifest['element_bytes'])
        for mapped, row in zip(user['address_indices'], data):
            records.append((mapped * manifest['token_bytes'], row.tobytes()))
    records.sort(key=lambda item: item[0])
    for variant in VARIANTS:
        folder = output/variant
        with (folder/'sw/softhier.elf').open('rb') as stream:
            elf = ELFFile(stream)
            symbol = elf.get_section_by_name('.symtab').get_symbol_by_name('saa_input')[0]
            input_address, input_size = symbol['st_value'], symbol['st_size']
        if not arch['cluster_tcdm_base'] <= input_address < input_address+input_size <= arch['cluster_tcdm_base']+arch['cluster_tcdm_size']:
            raise ValueError('Local index state exceeds TCDM')
        pad = (cfg['selected_tokens']+1) & ~1
        local = []
        for user in manifest['users']:
            words = [0x53414131, user['cluster'], cfg['selected_tokens'], cfg['context_tokens'],
                     manifest['token_bytes'], cfg['selection_seed'], int(user['checksum'], 16), user['index_checksum']]
            words += user['indices'] + [0]*(pad-cfg['selected_tokens'])
            words += user['address_indices'] + [0]*(pad-cfg['selected_tokens'])
            payload = np.array(words, dtype='<u4').tobytes()
            if len(payload) != input_size:
                raise ValueError('Local preload layout differs from compiled C structure')
            remote = arch['cluster_tcdm_remote'] + user['cluster']*arch['cluster_tcdm_size'] + input_address-arch['cluster_tcdm_base']
            local.append((remote, payload))
        # Split large meshes into multiple ELF files. The standard loader accepts
        # a binary list, avoiding both ELF's 16-bit segment-count limit and large
        # zero-filled gaps between randomly selected tokens.
        combined = sorted(records + local, key=lambda item: item[0])
        for left, right in zip(combined, combined[1:]):
            if left[0]+len(left[1]) > right[0]:
                raise ValueError('Preload address overlap')
        files = []
        for part, first in enumerate(range(0, len(combined), ELF_SEGMENT_LIMIT)):
            name = 'preload.elf' if part == 0 else f'preload_{part}.elf'
            write_elf(folder/name, combined[first:first+ELF_SEGMENT_LIMIT])
            files.append({'name':name, 'sha256':hashlib.sha256((folder/name).read_bytes()).hexdigest()})
        (folder/'preload.json').write_text(json.dumps({'local_input_addr': input_address,
            'local_index_addr': input_address+32+pad*4, 'input_size': input_size,
            'segments': len(combined), 'initialized_hbm_bytes': sum(len(data) for _,data in records),
            'files':files, 'sha256':files[0]['sha256']}, indent=2)+'\n')
        print(f'SAA_PRELOAD_PASS variant={variant} segments={len(combined)} files={len(files)} input_addr={input_address:#x}')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('action', choices=('prepare', 'preload'))
    parser.add_argument('arch', type=Path)
    parser.add_argument('kernel', type=Path)
    parser.add_argument('app', type=Path)
    parser.add_argument('output', type=Path)
    args = parser.parse_args()
    if args.action == 'prepare':
        prepare(args.arch, args.kernel, args.app, args.output)
    else:
        preload(args.output)
