//
// Copyright (C) 2026 ETH Zurich and University of Bologna
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Author: Chi Zhang <chizhang@ethz.ch>

#ifndef FLEXCLUSTERARCH_H
#define FLEXCLUSTERARCH_H

#define ARCH_NUM_CLUSTER_X 4
#define ARCH_NUM_CLUSTER_Y 4
#define ARCH_NUM_CORE_PER_CLUSTER 5
#define ARCH_CLUSTER_TCDM_BANK_WIDTH 32
#define ARCH_CLUSTER_TCDM_BANK_NB 128
#define ARCH_CLUSTER_TCDM_BASE 0x00000000
#define ARCH_CLUSTER_TCDM_SIZE 0x00060000
#define ARCH_CLUSTER_TCDM_REMOTE 0x30000000
#define ARCH_CLUSTER_STACK_BASE 0x10000000
#define ARCH_CLUSTER_STACK_SIZE 0x00020000
#define ARCH_CLUSTER_ZOMEM_BASE 0x18000000
#define ARCH_CLUSTER_ZOMEM_SIZE 0x00020000
#define ARCH_CLUSTER_REG_BASE 0x20000000
#define ARCH_CLUSTER_REG_SIZE 0x00000200
#define ARCH_SPATZ_ATTACED_CORES 4
#define ARCH_SPATZ_ATTACED_CHECK_LIST {1, 1, 1, 1, 0}
#define ARCH_SPATZ_ATTACED_SID_LIST {0, 1, 2, 3, 0}
#define ARCH_SPATZ_ATTACED_CORE_LIST {0, 1, 2, 3}
#define ARCH_SPATZ_NUM_VLSU_PORT 8
#define ARCH_SPATZ_NUM_FUNCTION_UNIT 4
#define ARCH_REDMULE_CE_HEIGHT 32
#define ARCH_REDMULE_CE_WIDTH 16
#define ARCH_REDMULE_CE_PIPE 1
#define ARCH_REDMULE_ELEM_SIZE 2
#define ARCH_REDMULE_QUEUE_DEPTH 1
#define ARCH_REDMULE_REG_BASE 0x20020000
#define ARCH_REDMULE_REG_SIZE 0x00000200
#define ARCH_IDMA_OUTSTAND_TXN 64
#define ARCH_IDMA_OUTSTAND_BURST 256
#define ARCH_HBM_START_BASE 0xc0000000
#define ARCH_HBM_NODE_ADDR_SPACE 0xc0000000
#define ARCH_NUM_NODE_PER_CTRL 4
#define ARCH_HBM_CHAN_PLACEMENT [4,0,0,4]
#define ARCH_HBM_NODE_ALIASE 4
#define ARCH_HBM_CTRL_XOR_SCRAMBLING 1
#define ARCH_NOC_OUTSTANDING 64
#define ARCH_NOC_LINK_WIDTH 1024
#define ARCH_INSTRUCTION_MEM_BASE 0x80000000
#define ARCH_INSTRUCTION_MEM_SIZE 0x00010000
#define ARCH_SOC_REGISTER_BASE 0x90000000
#define ARCH_SOC_REGISTER_SIZE 0x00010000
#define ARCH_SOC_REGISTER_EOC 0x90000000
#define ARCH_SOC_REGISTER_WAKEUP 0x90000004
#define ARCH_SYNC_BASE 0x40000000
#define ARCH_SYNC_INTERLEAVE 0x00000080
#define ARCH_SYNC_SPECIAL_MEM 0x00000040

#endif // FLEXCLUSTERARCH_H
